// SPDX-FileCopyrightText: 2026 njutest contributors
// SPDX-License-Identifier: MIT OR Apache-2.0

//! The closed, side-effect-free fragment that `verified-v1` may model check.
//!
//! This module does not infer purity from names or trust that a generated harness will happen to compile.
//! It accepts a deliberately small syntax,
//! rechecks both renderings, and emits private marker traits that make rustc re-establish the accepted input and output types in the Kani build.

#![expect(
    clippy::redundant_pub_crate,
    reason = "the module is crate-private by design and repeats that boundary on the typed API consumed by sibling runner modules"
)]

use std::collections::BTreeSet;

use proc_macro2::LineColumn;
use rust_mutants::catalog::Mutant;
use rust_mutants::span::Span;
use syn::visit::Visit as _;

use crate::config::Verified;

/// The only Kani release whose CLI and result schema this model contract accepts.
pub(crate) const KANI_VERSION: &str = "0.68.0";

/// The only exported document schema interpreted by [`result`].
pub(crate) const KANI_EXPORT_VERSION: &str = "1.0";

/// The build mode Kani 0.68 uses for verification artifacts.
pub(crate) const KANI_BUILD_MODE: &str = "release";

/// The rustc build embedded in the pinned Kani release.
pub(crate) const KANI_RUSTC_VERSION: &str = "rustc 1.100.0-nightly (8925ea358 2026-08-20)";

/// The CBMC banner exported by the pinned Kani release.
pub(crate) const KANI_CBMC_VERSION: &str = "6.11.0 (cbmc-6.11.0)";

/// The goto compiler banner exported by the pinned Kani release.
pub(crate) const KANI_GOTO_CC_VERSION: &str = "clang version 21.0.0 (goto-cc 6.11.0 (cbmc-6.11.0))";

/// The backend inside whatever the host compiler wrapped it in.
///
/// macOS clang writes `clang version 21.0.0 (goto-cc …)` and Linux gcc writes `gcc (goto-cc …) 13.3.0`, so the compiler Kani was built with is not the backend this pins.
pub(crate) const KANI_GOTO_CC_BACKEND: &str = "(goto-cc 6.11.0 (cbmc-6.11.0))";

/// The goto instrumentation banner exported by the pinned Kani release.
pub(crate) const KANI_GOTO_INSTRUMENT_VERSION: &str = "6.11.0 (cbmc-6.11.0)";

/// The one solver explicitly selected on every verified-v1 invocation.
pub(crate) const KANI_SOLVER: &str = "cadical";

/// The concise CBMC version in the exact two-line executable probe.
pub(crate) const KANI_BACKEND_VERSION: &str = "6.11.0";

/// The version of Kani's independently generated harness catalog.
pub(crate) const KANI_LIST_VERSION: &str = "0.1";

/// The only Cargo package identity compiled by the isolated proof crate.
pub(crate) const MODEL_PACKAGE: &str = "njutest-verified-model";

/// The language edition fixed by the isolated proof manifest.
pub(crate) const MODEL_EDITION: &str = "2024";

/// The only source path present in the isolated proof crate.
pub(crate) const MODEL_SOURCE_PATH: &str = "src/lib.rs";

/// The exact subprocess-environment construction bound into proof evidence.
pub(crate) const MODEL_ENVIRONMENT_POLICY: &str = "minimal-v1";

/// Dependency resolution is closed by a dependency-free exact lockfile and offline Cargo.
pub(crate) const MODEL_DEPENDENCY_POLICY: &str = "empty-lock-offline-v1";

/// The complete dependency-free manifest of the isolated proof crate.
pub(crate) const MODEL_MANIFEST: &str = "[package]\nname = \"njutest-verified-model\"\nversion = \"0.0.0\"\nedition = \"2024\"\npublish = false\nautobins = false\nautoexamples = false\nautotests = false\nautobenches = false\n\n[lib]\npath = \"src/lib.rs\"\n\n[workspace]\n";

/// The complete lockfile of the dependency-free isolated proof crate.
pub(crate) const MODEL_LOCK: &str = "# This file is automatically @generated by Cargo.\n# It is not intended for manual editing.\nversion = 4\n\n[[package]]\nname = \"njutest-verified-model\"\nversion = \"0.0.0\"\n";

const MODEL_CRATE_DIGEST_DOMAIN: &str = "njutest-model-crate-v1";

const ASSERTION_PREFIX: &str = "njutest-model-v1:";

mod phase;
pub(crate) mod result;
pub(crate) mod runner;

pub(crate) use phase::{
    Decided, ModelError, Plan, Preparation, Proving, confirm_not_required, prove,
};

/// Which rendering an eligibility failure came from.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub(crate) enum Rendering {
    /// The pristine function.
    Original,
    /// The function after the candidate edit.
    Mutant,
}

/// A function-shape feature outside the verified fragment.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub(crate) enum FunctionFeature {
    /// Type or lifetime parameters, or a where clause.
    Generic,
    /// A const function.
    Const,
    /// An async function.
    Async,
    /// An unsafe function.
    Unsafe,
    /// An explicitly `safe fn`; the fragment fixes one spelling of safety.
    ExplicitSafe,
    /// A non-Rust ABI.
    Extern,
    /// A variadic signature.
    Variadic,
    /// A receiver rather than a free-function argument.
    Receiver,
}

/// A type feature outside the closed symbolic domain.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub(crate) enum TypeFeature {
    /// A reference could observe aliasing or external state.
    Reference,
    /// A raw pointer has provenance and memory effects outside this model.
    RawPointer,
    /// A slice is unsized and is not minted by value.
    Slice,
    /// A function pointer may call code outside the fragment.
    FunctionPointer,
    /// A trait object has an open implementation set.
    TraitObject,
    /// An `impl Trait` has an intentionally hidden concrete type.
    ImplTrait,
    /// The never type produces no comparable result.
    Never,
    /// A macro can expand the type domain after this audit.
    Macro,
    /// An inferred type does not state the model's domain.
    Infer,
    /// A named type is outside the closed primitive and `Option` set.
    Named,
    /// An array length is not a concrete integer literal.
    ArrayLength,
    /// The tuple is wider than the implementations emitted by this version.
    TupleWidth,
    /// A float result is not reflexive under `Eq` because of NaN.
    NonReflexiveFloat,
    /// `usize` and `isize` change their domain with the compilation target.
    TargetSized,
    /// Syntax added after this closed set was written.
    Unsupported,
}

/// An effect or open semantic edge outside the pure expression fragment.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub(crate) enum Effect {
    /// Arithmetic, shifts, and negation depend on the profile's overflow semantics; Kani 0.68 exports a release build and cannot witness the measured test profile through its result protocol.
    ProfileDependentArithmetic,
    /// A free call, including recursion.
    Call,
    /// A method call whose implementation is open.
    MethodCall,
    /// A macro expansion not present in the audited tree.
    Macro,
    /// A path not bound by an argument or local.
    GlobalPath,
    /// A closure can capture state and creates a new callable body.
    Closure,
    /// Async or await introduces a state machine and executor interaction.
    Async,
    /// An unsafe block changes the memory model.
    Unsafe,
    /// A reference creates aliasing that this fragment does not model.
    Reference,
    /// A raw address exposes provenance.
    RawAddress,
    /// A `for` loop invokes the open `IntoIterator` trait.
    ForLoop,
    /// A range constructs an open library type.
    Range,
    /// A struct literal names a type outside the closed domain.
    Struct,
    /// `?` or a try block invokes open conversion machinery.
    Try,
    /// A match requires variant patterns outside this first closed fragment.
    Match,
    /// A pattern is not a plain local binding or wildcard.
    Pattern,
    /// A nested item has separate name resolution and callable state.
    NestedItem,
    /// A string-like literal allocates or borrows storage outside the scalar domain.
    Literal,
    /// A dereference observes memory through an alias.
    Dereference,
    /// A named field requires a named aggregate outside the type domain.
    NamedField,
    /// Syntax added after this closed set was written.
    Unsupported,
}

/// The stable, exhaustive classes of eligibility refusal.
#[derive(Debug, Clone, Copy, PartialEq, Eq, njutest_macros::AllVariants)]
pub(crate) enum IneligibilityKind {
    /// Source bytes are not Rust UTF-8 text.
    SourceEncoding,
    /// The candidate was minted from different source bytes.
    SourceDigest,
    /// The candidate's own identity fields disagree.
    Candidate,
    /// The cataloged ID is not the candidate's derived ID.
    Identity,
    /// The pristine source does not parse.
    SourceSyntax,
    /// The edit is not inside one top-level free function body.
    EnclosingFunction,
    /// Function modifiers are outside the fragment.
    FunctionShape,
    /// The function has no symbolic input.
    NoSymbolicInput,
    /// An argument pattern is not a plain by-value binding.
    ArgumentPattern,
    /// An input type is outside the symbolic domain.
    InputType,
    /// The output type is outside the equality domain.
    OutputType,
    /// The pristine or mutant body is not in the pure fragment.
    Effect,
    /// The edited function does not parse.
    MutantSyntax,
    /// A generated private name already occurs in the source.
    NameCollision,
    /// A source span could not be mapped back to bytes.
    SourceSpan,
}

/// Why one mutation cannot enter the model checker.
#[derive(Debug, Clone, PartialEq, Eq)]
pub(crate) enum Ineligible {
    /// The source is not UTF-8.
    SourceEncoding,
    /// The source digest no longer matches the candidate.
    SourceDigest,
    /// The candidate is internally incoherent.
    Candidate,
    /// The cataloged identity differs from the independently derived one.
    Identity,
    /// The source is not a parseable Rust file.
    SourceSyntax,
    /// The edit is not wholly inside exactly one top-level free function body.
    EnclosingFunction,
    /// The signature carries a forbidden modifier.
    FunctionShape(FunctionFeature),
    /// There is no input for a symbolic differential question.
    NoSymbolicInput,
    /// An argument is not a plain by-value local binding.
    ArgumentPattern { index: usize },
    /// One input is outside the closed domain.
    InputType { index: usize, feature: TypeFeature },
    /// The result is outside the closed equality domain.
    OutputType(TypeFeature),
    /// One rendering contains an effect or open semantic edge.
    Effect {
        rendering: Rendering,
        effect: Effect,
    },
    /// The candidate edit does not produce a parseable function.
    MutantSyntax,
    /// A deterministic generated name already exists in the subject.
    NameCollision,
    /// Parser locations did not map to the source bytes.
    SourceSpan,
}

impl Ineligible {
    /// The stable class later reports and audit schemas switch over.
    pub(crate) const fn kind(&self) -> IneligibilityKind {
        match self {
            Self::SourceEncoding => IneligibilityKind::SourceEncoding,
            Self::SourceDigest => IneligibilityKind::SourceDigest,
            Self::Candidate => IneligibilityKind::Candidate,
            Self::Identity => IneligibilityKind::Identity,
            Self::SourceSyntax => IneligibilityKind::SourceSyntax,
            Self::EnclosingFunction => IneligibilityKind::EnclosingFunction,
            Self::FunctionShape(_) => IneligibilityKind::FunctionShape,
            Self::NoSymbolicInput => IneligibilityKind::NoSymbolicInput,
            Self::ArgumentPattern { .. } => IneligibilityKind::ArgumentPattern,
            Self::InputType { .. } => IneligibilityKind::InputType,
            Self::OutputType(_) => IneligibilityKind::OutputType,
            Self::Effect { .. } => IneligibilityKind::Effect,
            Self::MutantSyntax => IneligibilityKind::MutantSyntax,
            Self::NameCollision => IneligibilityKind::NameCollision,
            Self::SourceSpan => IneligibilityKind::SourceSpan,
        }
    }
}

/// A generated, self-identifying Kani differential harness.
#[derive(Debug, Clone, PartialEq, Eq)]
pub(crate) struct Harness {
    source: String,
    name: String,
    assertion_tag: String,
    mutant_id: String,
    source_digest: String,
    rendered_digest: String,
    crate_digest: String,
    path: String,
    rule: String,
    rule_version: u32,
    span: Span,
    original_hex: String,
    replacement_hex: String,
    unwind: std::num::NonZeroU32,
    timeout_ms: std::num::NonZeroU64,
}

impl Harness {
    /// The complete temporary Rust source handed to Kani.
    pub(crate) fn source(&self) -> &str {
        &self.source
    }

    /// The globally unique harness suffix selected by Kani and then checked against the one fully-qualified result the export names.
    pub(crate) fn harness_name(&self) -> &str {
        &self.name
    }

    /// The property description that the result parser must find exactly once.
    pub(crate) fn assertion_tag(&self) -> &str {
        &self.assertion_tag
    }

    /// The full stable mutant identity.
    pub(crate) fn mutant_id(&self) -> &str {
        &self.mutant_id
    }

    /// The workspace-relative path which participates in the mutation identity.
    pub(crate) fn path(&self) -> &str {
        &self.path
    }

    /// The canonical mutation operator name.
    pub(crate) fn rule(&self) -> &str {
        &self.rule
    }

    /// The mutation operator version which participates in the identity.
    pub(crate) const fn rule_version(&self) -> u32 {
        self.rule_version
    }

    /// The pristine-source byte span replaced by the mutation.
    pub(crate) const fn span(&self) -> Span {
        self.span
    }

    /// Hexadecimal pristine bytes covered by [`Self::span`].
    pub(crate) fn original_hex(&self) -> &str {
        &self.original_hex
    }

    /// Hexadecimal replacement bytes used for the mutant rendering.
    pub(crate) fn replacement_hex(&self) -> &str {
        &self.replacement_hex
    }

    /// The digest of the pristine source from which eligibility was decided.
    pub(crate) fn source_digest(&self) -> &str {
        &self.source_digest
    }

    /// The digest of the generated source that the runner must execute.
    pub(crate) fn rendered_digest(&self) -> &str {
        &self.rendered_digest
    }

    /// Domain-separated digest of the exact manifest, lockfile, and generated source which form the dependency-free proof crate.
    pub(crate) fn crate_digest(&self) -> &str {
        &self.crate_digest
    }

    /// The nonzero unwind encoded directly on the generated proof harness.
    pub(crate) const fn unwind(&self) -> std::num::NonZeroU32 {
        self.unwind
    }

    /// The nonzero wall-clock ceiling the runner must impose externally.
    pub(crate) const fn timeout(&self) -> std::time::Duration {
        std::time::Duration::from_millis(self.timeout_ms.get())
    }

    /// The exact nonzero millisecond representation retained in proof evidence.
    pub(crate) const fn timeout_ms(&self) -> std::num::NonZeroU64 {
        self.timeout_ms
    }

    #[cfg(all(test, unix))]
    pub(crate) const fn set_timeout_for_test(&mut self, timeout_ms: std::num::NonZeroU64) {
        self.timeout_ms = timeout_ms;
    }
}

#[derive(Debug, Clone, PartialEq, Eq)]
enum SymbolicType {
    Unit,
    Scalar(&'static str),
    Float(&'static str),
    Option(Box<Self>),
    Array(Box<Self>, usize),
    Tuple(Vec<Self>),
}

impl SymbolicType {
    fn canonical(&self, core_crate: &str) -> String {
        match self {
            Self::Unit => "()".to_owned(),
            Self::Scalar(name) | Self::Float(name) => {
                format!("{core_crate}::primitive::{name}")
            }
            Self::Option(inner) => {
                format!(
                    "{core_crate}::option::Option<{}>",
                    inner.canonical(core_crate)
                )
            }
            Self::Array(inner, len) => format!("[{}; {len}]", inner.canonical(core_crate)),
            Self::Tuple(elements) => {
                let mut rendered = String::from("(");
                for (index, element) in elements.iter().enumerate() {
                    if index > 0 {
                        rendered.push_str(", ");
                    }
                    rendered.push_str(&element.canonical(core_crate));
                }
                if elements.len() == 1 {
                    rendered.push(',');
                }
                rendered.push(')');
                rendered
            }
        }
    }

    fn output_safe(&self) -> Result<(), TypeFeature> {
        match self {
            Self::Float(_) => Err(TypeFeature::NonReflexiveFloat),
            Self::Option(inner) | Self::Array(inner, _) => inner.output_safe(),
            Self::Tuple(elements) => elements.iter().try_for_each(Self::output_safe),
            Self::Unit | Self::Scalar(_) => Ok(()),
        }
    }
}

#[derive(Debug, Clone, Copy)]
struct FunctionBytes {
    function: Span,
    body: Span,
    name: Span,
}

/// Why a harness was not generated: the mutant is not one the fragment admits, or its source could not be read at all.
#[derive(Debug)]
enum Generation {
    Ineligible(Ineligible),
    Unread(rust_mutants::parsing::ReadingError),
}

impl From<Ineligible> for Generation {
    fn from(why: Ineligible) -> Self {
        Self::Ineligible(why)
    }
}

impl Generation {
    /// A reading failure: text that is not Rust as `syntax`, and a reading that could not happen as itself.
    fn read(unread: rust_mutants::parsing::ReadingError, syntax: Ineligible) -> Self {
        match unread.syntax() {
            Ok(_not_rust) => Self::Ineligible(syntax),
            Err(unreadable) => Self::Unread(unreadable),
        }
    }
}

/// The harness for `mutant`, or why the fragment does not admit it, read on a thread of its own.
///
/// # Errors
/// The source could not be read at all, which is a failure of the run rather than an answer about the mutant.
pub(crate) fn generate(
    source: &[u8],
    mutant: &Mutant,
    verified: Verified,
) -> Result<Result<Harness, Ineligible>, rust_mutants::parsing::ReadingError> {
    match rust_mutants::parsing::apart(|parsing| generate_with(parsing, source, mutant, verified))?
    {
        Ok(harness) => Ok(Ok(harness)),
        Err(Generation::Ineligible(why)) => Ok(Err(why)),
        Err(Generation::Unread(unread)) => Err(unread),
    }
}

/// Decides eligibility and emits a Kani harness for both renderings.
///
/// # Errors
/// Returns a closed, typed refusal for every source, signature, type, or body feature not proven safe by this version of the fragment.
#[expect(
    clippy::too_many_lines,
    reason = "the one admission transaction rederives identity, audits both renderings, and binds every generated proof name before returning"
)]
fn generate_with(
    parsing: &rust_mutants::parsing::Parsing,
    source: &[u8],
    mutant: &Mutant,
    verified: Verified,
) -> Result<Harness, Generation> {
    let source_text = std::str::from_utf8(source).map_err(|_error| Ineligible::SourceEncoding)?;
    let candidate = &mutant.candidate;
    if rust_mutants::id::digest(source) != candidate.source_digest {
        return Err(Ineligible::SourceDigest.into());
    }
    candidate
        .validate()
        .map_err(|_error| Ineligible::Candidate)?;
    let derived_id = candidate.id().map_err(|_error| Ineligible::Candidate)?;
    if derived_id != mutant.id {
        return Err(Ineligible::Identity.into());
    }
    if candidate
        .span
        .slice(source)
        .map_err(|_error| Ineligible::Candidate)?
        != candidate.original
    {
        return Err(Ineligible::Candidate.into());
    }

    let file = parsing
        .file(source_text)
        .map_err(|unread| Generation::read(unread, Ineligible::SourceSyntax))?;
    let (item, bytes) = enclosing_function(source_text, &file, candidate.span)?;
    check_function_shape(&item.sig)?;
    check_source_context(&file, &item.sig)?;
    check_attributes(item, Rendering::Original)?;
    let (inputs, output, argument_names) = signature(&item.sig)?;
    check_body(&item.block, &argument_names, Rendering::Original)?;

    let function_source = slice(source_text, bytes.function)?;
    let relative_edit = relative(candidate.span, bytes.function)?;
    let (mutated, edit_map) = rust_mutants::splice::apply(
        function_source.as_bytes(),
        &[rust_mutants::splice::Splice {
            span: relative_edit,
            original: candidate.original.clone(),
            replacement: candidate.replacement.clone(),
        }],
    )
    .map_err(|_error| Ineligible::MutantSyntax)?;
    let source_len =
        u32::try_from(function_source.len()).map_err(|_overflow| Ineligible::MutantSyntax)?;
    let mutated_len = u32::try_from(mutated.len()).map_err(|_overflow| Ineligible::MutantSyntax)?;
    if edit_map.splices() != 1
        || edit_map.src_len() != source_len
        || edit_map.out_len() != mutated_len
    {
        return Err(Ineligible::MutantSyntax.into());
    }
    let mutated_text = std::str::from_utf8(&mutated).map_err(|_error| Ineligible::MutantSyntax)?;
    let mutated_item: syn::ItemFn = parsing
        .read(mutated_text)
        .map_err(|unread| Generation::read(unread, Ineligible::MutantSyntax))?;
    check_function_shape(&mutated_item.sig)?;
    check_attributes(&mutated_item, Rendering::Mutant)?;
    check_body(&mutated_item.block, &argument_names, Rendering::Mutant)?;

    let suffix = &mutant.id;
    let harness_name = format!("__njutest_model_{suffix}");
    let original_name = format!("__njutest_original_{suffix}");
    let mutant_name = format!("__njutest_mutant_{suffix}");
    let input_trait = format!("NjutestInput{suffix}");
    let output_trait = format!("NjutestOutput{suffix}");
    let kani_crate = format!("__njutest_kani_{suffix}");
    let core_crate = format!("__njutest_core_{suffix}");
    let any_name = format!("__njutest_any_{suffix}");
    let same_name = format!("__njutest_same_{suffix}");
    for generated in [
        &harness_name,
        &original_name,
        &mutant_name,
        &input_trait,
        &output_trait,
        &kani_crate,
        &core_crate,
        &any_name,
        &same_name,
    ] {
        if source_text.contains(generated) {
            return Err(Ineligible::NameCollision.into());
        }
    }

    let name_relative = relative(bytes.name, bytes.function)?;
    let original_clone = renamed(function_source, name_relative, &original_name)?;
    let mutant_clone = renamed(mutated_text, name_relative, &mutant_name)?;
    let assertion_tag = format!("{ASSERTION_PREFIX}{}", mutant.id);
    let generated = render(
        source_text,
        &original_clone,
        &mutant_clone,
        &inputs,
        &output,
        &harness_name,
        &original_name,
        &mutant_name,
        &input_trait,
        &output_trait,
        &kani_crate,
        &core_crate,
        &any_name,
        &same_name,
        &assertion_tag,
        verified,
    );
    let rendered_digest = rust_mutants::id::digest(generated.as_bytes());
    let crate_digest = model_crate_digest(generated.as_bytes());
    Ok(Harness {
        source: generated,
        name: harness_name,
        assertion_tag,
        mutant_id: mutant.id.to_string(),
        source_digest: candidate.source_digest.clone(),
        rendered_digest,
        crate_digest,
        path: candidate.path.clone(),
        rule: candidate.rule.name.to_owned(),
        rule_version: candidate.rule.version,
        span: candidate.span,
        original_hex: hex::encode(&candidate.original),
        replacement_hex: hex::encode(&candidate.replacement),
        unwind: verified.unwind(),
        timeout_ms: verified.timeout_ms(),
    })
}

/// Re-derives the immutable input identity of the isolated proof crate.
///
/// Each file is represented by its SHA-256 before the outer, domain-separated digest is computed.
/// The fixed names and fixed-width inner digests make the ledger unambiguous without trusting filesystem enumeration order.
pub(crate) fn model_crate_digest(source: &[u8]) -> String {
    model_crate_digest_from_rendered_digest(&rust_mutants::id::digest(source))
}

/// Computes the same proof-crate identity from an already checked generated source digest.
/// This lets the durable report type enforce the relation without retaining source bytes inside the JSON document itself.
pub(crate) fn model_crate_digest_from_rendered_digest(source: &str) -> String {
    let manifest = rust_mutants::id::digest(MODEL_MANIFEST.as_bytes());
    let lock = rust_mutants::id::digest(MODEL_LOCK.as_bytes());
    let ledger = format!(
        "{MODEL_CRATE_DIGEST_DOMAIN}\nenvironment:{MODEL_ENVIRONMENT_POLICY}\ndependency-resolution:{MODEL_DEPENDENCY_POLICY}\nCargo.toml:{manifest}\nCargo.lock:{lock}\n{MODEL_SOURCE_PATH}:{source}\n"
    );
    rust_mutants::id::digest(ledger.as_bytes())
}

fn enclosing_function<'file>(
    source: &str,
    file: &'file syn::File,
    mutation: Span,
) -> Result<(&'file syn::ItemFn, FunctionBytes), Ineligible> {
    for item in &file.items {
        let syn::Item::Fn(function) = item else {
            continue;
        };
        let bytes = function_bytes(source, function)?;
        if bytes.function.contains(mutation) {
            if bytes.body.contains(mutation) {
                return Ok((function, bytes));
            }
            return Err(Ineligible::EnclosingFunction);
        }
    }
    Err(Ineligible::EnclosingFunction)
}

fn function_bytes(source: &str, function: &syn::ItemFn) -> Result<FunctionBytes, Ineligible> {
    let function_start = offset(source, function.sig.fn_token.span.start())?;
    let function_end = offset(source, function.block.brace_token.span.close().end())?;
    let body_start = offset(source, function.block.brace_token.span.open().end())?;
    let body_end = offset(source, function.block.brace_token.span.close().start())?;
    let name_start = offset(source, function.sig.ident.span().start())?;
    let name_end = offset(source, function.sig.ident.span().end())?;
    Ok(FunctionBytes {
        function: Span::new(function_start, function_end)
            .map_err(|_error| Ineligible::SourceSpan)?,
        body: Span::new(body_start, body_end).map_err(|_error| Ineligible::SourceSpan)?,
        name: Span::new(name_start, name_end).map_err(|_error| Ineligible::SourceSpan)?,
    })
}

fn offset(source: &str, location: LineColumn) -> Result<u32, Ineligible> {
    let mut line = 1usize;
    let mut base = 0usize;
    for part in source.split_inclusive('\n') {
        if line == location.line {
            let byte = base
                .checked_add(location.column)
                .ok_or(Ineligible::SourceSpan)?;
            if byte <= source.len() && source.is_char_boundary(byte) {
                return u32::try_from(byte).map_err(|_error| Ineligible::SourceSpan);
            }
            return Err(Ineligible::SourceSpan);
        }
        base = base.checked_add(part.len()).ok_or(Ineligible::SourceSpan)?;
        line = line.checked_add(1).ok_or(Ineligible::SourceSpan)?;
    }
    if location.line == line && location.column == 0 {
        return u32::try_from(base).map_err(|_error| Ineligible::SourceSpan);
    }
    Err(Ineligible::SourceSpan)
}

fn slice(source: &str, span: Span) -> Result<&str, Ineligible> {
    let bytes = span
        .slice(source.as_bytes())
        .map_err(|_error| Ineligible::SourceSpan)?;
    std::str::from_utf8(bytes).map_err(|_error| Ineligible::SourceSpan)
}

fn relative(inner: Span, outer: Span) -> Result<Span, Ineligible> {
    if !outer.contains(inner) {
        return Err(Ineligible::SourceSpan);
    }
    let start = inner
        .start
        .checked_sub(outer.start)
        .ok_or(Ineligible::SourceSpan)?;
    let end = inner
        .end
        .checked_sub(outer.start)
        .ok_or(Ineligible::SourceSpan)?;
    Span::new(start, end).map_err(|_error| Ineligible::SourceSpan)
}

fn renamed(function: &str, name: Span, replacement: &str) -> Result<String, Ineligible> {
    let start = usize::try_from(name.start).map_err(|_error| Ineligible::SourceSpan)?;
    let end = usize::try_from(name.end).map_err(|_error| Ineligible::SourceSpan)?;
    if !function.is_char_boundary(start) || !function.is_char_boundary(end) {
        return Err(Ineligible::SourceSpan);
    }
    let mut renamed = function.to_owned();
    renamed.replace_range(start..end, replacement);
    Ok(renamed)
}

fn check_function_shape(signature: &syn::Signature) -> Result<(), Ineligible> {
    if !signature.generics.params.is_empty() || signature.generics.where_clause.is_some() {
        return Err(Ineligible::FunctionShape(FunctionFeature::Generic));
    }
    if signature.constness.is_some() {
        return Err(Ineligible::FunctionShape(FunctionFeature::Const));
    }
    if signature.asyncness.is_some() {
        return Err(Ineligible::FunctionShape(FunctionFeature::Async));
    }
    match signature.safety {
        syn::Safety::Unsafe(_) => {
            return Err(Ineligible::FunctionShape(FunctionFeature::Unsafe));
        }
        syn::Safety::Safe(_) => {
            return Err(Ineligible::FunctionShape(FunctionFeature::ExplicitSafe));
        }
        syn::Safety::Default => {}
    }
    if signature.abi.is_some() {
        return Err(Ineligible::FunctionShape(FunctionFeature::Extern));
    }
    if signature.variadic.is_some() {
        return Err(Ineligible::FunctionShape(FunctionFeature::Variadic));
    }
    Ok(())
}

fn signature(
    signature: &syn::Signature,
) -> Result<(Vec<SymbolicType>, SymbolicType, BTreeSet<String>), Ineligible> {
    if signature.inputs.is_empty() {
        return Err(Ineligible::NoSymbolicInput);
    }
    let mut inputs = Vec::with_capacity(signature.inputs.len());
    let mut names = BTreeSet::new();
    for (index, argument) in signature.inputs.iter().enumerate() {
        let syn::FnArg::Typed(typed) = argument else {
            return Err(Ineligible::FunctionShape(FunctionFeature::Receiver));
        };
        let syn::Pat::Ident(binding) = typed.pat.as_ref() else {
            return Err(Ineligible::ArgumentPattern { index });
        };
        if binding.by_ref.is_some() || binding.subpat.is_some() {
            return Err(Ineligible::ArgumentPattern { index });
        }
        names.insert(binding.ident.to_string());
        let symbolic =
            symbolic_type(&typed.ty).map_err(|feature| Ineligible::InputType { index, feature })?;
        inputs.push(symbolic);
    }
    let output = match &signature.output {
        syn::ReturnType::Default => SymbolicType::Unit,
        syn::ReturnType::Type(_arrow, output) => {
            symbolic_type(output).map_err(Ineligible::OutputType)?
        }
    };
    output.output_safe().map_err(Ineligible::OutputType)?;
    Ok((inputs, output, names))
}

fn symbolic_type(held: &syn::Type) -> Result<SymbolicType, TypeFeature> {
    match held {
        syn::Type::Tuple(tuple) if tuple.elems.is_empty() => Ok(SymbolicType::Unit),
        syn::Type::Tuple(tuple) if tuple.elems.len() <= 4 => tuple
            .elems
            .iter()
            .map(symbolic_type)
            .collect::<Result<Vec<_>, _>>()
            .map(SymbolicType::Tuple),
        syn::Type::Tuple(_) => Err(TypeFeature::TupleWidth),
        syn::Type::Array(array) => {
            let syn::Expr::Lit(length) = &array.len else {
                return Err(TypeFeature::ArrayLength);
            };
            let syn::Lit::Int(length) = &length.lit else {
                return Err(TypeFeature::ArrayLength);
            };
            let length = length
                .base10_parse::<usize>()
                .map_err(|_error| TypeFeature::ArrayLength)?;
            Ok(SymbolicType::Array(
                Box::new(symbolic_type(&array.elem)?),
                length,
            ))
        }
        syn::Type::Path(path) if path.qself.is_none() => symbolic_path(&path.path),
        syn::Type::Paren(inner) => symbolic_type(&inner.elem),
        syn::Type::Group(inner) => symbolic_type(&inner.elem),
        syn::Type::Reference(_) => Err(TypeFeature::Reference),
        syn::Type::Ptr(_) => Err(TypeFeature::RawPointer),
        syn::Type::Slice(_) => Err(TypeFeature::Slice),
        syn::Type::FnPtr(_) => Err(TypeFeature::FunctionPointer),
        syn::Type::TraitObject(_) => Err(TypeFeature::TraitObject),
        syn::Type::ImplTrait(_) => Err(TypeFeature::ImplTrait),
        syn::Type::Never(_) => Err(TypeFeature::Never),
        syn::Type::Macro(_) => Err(TypeFeature::Macro),
        syn::Type::Infer(_) => Err(TypeFeature::Infer),
        _ => Err(TypeFeature::Unsupported),
    }
}

fn symbolic_path(path: &syn::Path) -> Result<SymbolicType, TypeFeature> {
    let segments = path.segments.iter().collect::<Vec<_>>();
    let primitive_name = match segments.as_slice() {
        [one] if matches!(one.arguments, syn::PathArguments::None) => Some(one.ident.to_string()),
        [root, middle, one]
            if (root.ident == "core" || root.ident == "std")
                && middle.ident == "primitive"
                && matches!(root.arguments, syn::PathArguments::None)
                && matches!(middle.arguments, syn::PathArguments::None)
                && matches!(one.arguments, syn::PathArguments::None) =>
        {
            Some(one.ident.to_string())
        }
        _ => None,
    };
    if primitive_name
        .as_deref()
        .is_some_and(|name| matches!(name, "usize" | "isize"))
    {
        return Err(TypeFeature::TargetSized);
    }
    let primitive = primitive_name.as_deref().and_then(primitive);
    if let Some(primitive) = primitive {
        return Ok(primitive);
    }

    let option = match segments.as_slice() {
        [one] if one.ident == "Option" => Some(*one),
        [root, middle, one]
            if (root.ident == "core" || root.ident == "std")
                && middle.ident == "option"
                && one.ident == "Option" =>
        {
            Some(*one)
        }
        _ => None,
    };
    let Some(option) = option else {
        return Err(TypeFeature::Named);
    };
    let syn::PathArguments::AngleBracketed(arguments) = &option.arguments else {
        return Err(TypeFeature::Named);
    };
    let mut arguments = arguments.args.iter();
    let Some(syn::GenericArgument::Type(inner)) = arguments.next() else {
        return Err(TypeFeature::Named);
    };
    if arguments.next().is_some() {
        return Err(TypeFeature::Named);
    }
    Ok(SymbolicType::Option(Box::new(symbolic_type(inner)?)))
}

fn primitive(name: &str) -> Option<SymbolicType> {
    match name {
        "bool" => Some(SymbolicType::Scalar("bool")),
        "char" => Some(SymbolicType::Scalar("char")),
        "i8" => Some(SymbolicType::Scalar("i8")),
        "i16" => Some(SymbolicType::Scalar("i16")),
        "i32" => Some(SymbolicType::Scalar("i32")),
        "i64" => Some(SymbolicType::Scalar("i64")),
        "i128" => Some(SymbolicType::Scalar("i128")),
        "u8" => Some(SymbolicType::Scalar("u8")),
        "u16" => Some(SymbolicType::Scalar("u16")),
        "u32" => Some(SymbolicType::Scalar("u32")),
        "u64" => Some(SymbolicType::Scalar("u64")),
        "u128" => Some(SymbolicType::Scalar("u128")),
        "f32" => Some(SymbolicType::Float("f32")),
        "f64" => Some(SymbolicType::Float("f64")),
        _ => None,
    }
}

#[derive(Default)]
struct TypeRootAudit {
    names: BTreeSet<String>,
}

impl<'ast> syn::visit::Visit<'ast> for TypeRootAudit {
    fn visit_type_path(&mut self, path: &'ast syn::TypePath) {
        if path.qself.is_none()
            && let Some(root) = path.path.segments.first()
        {
            self.names.insert(root.ident.to_string());
        }
        syn::visit::visit_type_path(self, path);
    }
}

/// The extracted function must resolve every admitted type spelling exactly as it did in the subject crate.
/// A root binding or open import can otherwise turn a syntactically primitive type into an unrelated user type before the isolated proof crate canonicalizes it.
fn check_source_context(file: &syn::File, signature: &syn::Signature) -> Result<(), Ineligible> {
    let mut attributes = AttributeAudit::default();
    attributes.visit_file(file);
    if attributes.forbidden {
        return Err(Ineligible::Effect {
            rendering: Rendering::Original,
            effect: Effect::Unsupported,
        });
    }

    let mut roots = TypeRootAudit::default();
    roots.visit_signature(signature);
    if file
        .items
        .iter()
        .any(|item| item_conflicts_with_type_roots(item, &roots.names))
    {
        return Err(Ineligible::NameCollision);
    }
    Ok(())
}

fn item_conflicts_with_type_roots(item: &syn::Item, roots: &BTreeSet<String>) -> bool {
    match item {
        syn::Item::Const(item) => roots.contains(&item.ident.to_string()),
        syn::Item::Enum(item) => roots.contains(&item.ident.to_string()),
        syn::Item::ExternCrate(item) => {
            let bound = item
                .rename
                .as_ref()
                .map_or(&item.ident, |(_as, rename)| rename);
            roots.contains(&bound.to_string())
        }
        syn::Item::Fn(item) => roots.contains(&item.sig.ident.to_string()),
        syn::Item::ForeignMod(_) | syn::Item::Impl(_) => false,
        syn::Item::Mod(item) => roots.contains(&item.ident.to_string()),
        syn::Item::Static(item) => roots.contains(&item.ident.to_string()),
        syn::Item::Struct(item) => roots.contains(&item.ident.to_string()),
        syn::Item::Trait(item) => roots.contains(&item.ident.to_string()),
        syn::Item::TraitAlias(item) => roots.contains(&item.ident.to_string()),
        syn::Item::Type(item) => roots.contains(&item.ident.to_string()),
        syn::Item::Union(item) => roots.contains(&item.ident.to_string()),
        syn::Item::Use(item) => use_tree_conflicts(&item.tree, roots),
        _ => true,
    }
}

fn use_tree_conflicts(tree: &syn::UseTree, roots: &BTreeSet<String>) -> bool {
    match tree {
        syn::UseTree::Path(path) => use_tree_conflicts(&path.tree, roots),
        syn::UseTree::Name(name) => roots.contains(&name.ident.to_string()),
        syn::UseTree::Rename(rename) => roots.contains(&rename.rename.to_string()),
        syn::UseTree::Glob(_) => true,
        syn::UseTree::Group(group) => group
            .items
            .iter()
            .any(|item| use_tree_conflicts(item, roots)),
    }
}

#[derive(Default)]
struct AttributeAudit {
    forbidden: bool,
}

impl<'ast> syn::visit::Visit<'ast> for AttributeAudit {
    fn visit_attribute(&mut self, attribute: &'ast syn::Attribute) {
        if !literal_doc_attribute(attribute) {
            self.forbidden = true;
        }
    }
}

fn literal_doc_attribute(attribute: &syn::Attribute) -> bool {
    match &attribute.meta {
        syn::Meta::NameValue(value) if value.path.is_ident("doc") => {
            matches!(
                &value.value,
                syn::Expr::Lit(syn::ExprLit {
                    lit: syn::Lit::Str(_),
                    ..
                })
            )
        }
        syn::Meta::Path(_) | syn::Meta::List(_) | syn::Meta::NameValue(_) => false,
    }
}

fn check_attributes(item: &syn::ItemFn, rendering: Rendering) -> Result<(), Ineligible> {
    let mut audit = AttributeAudit::default();
    audit.visit_item_fn(item);
    if audit.forbidden {
        return Err(Ineligible::Effect {
            rendering,
            effect: Effect::Unsupported,
        });
    }
    Ok(())
}

struct Purity {
    scopes: Vec<BTreeSet<String>>,
    rendering: Rendering,
}

impl Purity {
    const fn reject<T>(&self, effect: Effect) -> Result<T, Ineligible> {
        Err(Ineligible::Effect {
            rendering: self.rendering,
            effect,
        })
    }

    fn local(&self, name: &str) -> bool {
        self.scopes.iter().rev().any(|scope| scope.contains(name))
    }

    fn block(&mut self, block: &syn::Block) -> Result<(), Ineligible> {
        self.scopes.push(BTreeSet::new());
        for statement in &block.stmts {
            self.statement(statement)?;
        }
        match self.scopes.pop() {
            Some(_completed_scope) => Ok(()),
            None => self.reject(Effect::Unsupported),
        }
    }

    fn statement(&mut self, statement: &syn::Stmt) -> Result<(), Ineligible> {
        match statement {
            syn::Stmt::Expr(expression, _semi) => self.expression(expression),
            syn::Stmt::Local(local) => {
                let Some(initializer) = &local.init else {
                    return self.reject(Effect::Pattern);
                };
                if initializer.diverge.is_some() {
                    return self.reject(Effect::Pattern);
                }
                self.expression(&initializer.expr)?;
                let name = local_name(&local.pat).ok_or(Ineligible::Effect {
                    rendering: self.rendering,
                    effect: Effect::Pattern,
                })?;
                let Some(scope) = self.scopes.last_mut() else {
                    return self.reject(Effect::Unsupported);
                };
                scope.insert(name);
                Ok(())
            }
            syn::Stmt::Item(_) => self.reject(Effect::NestedItem),
            syn::Stmt::Macro(_) => self.reject(Effect::Macro),
        }
    }

    #[expect(
        clippy::too_many_lines,
        reason = "a single exhaustive syntax gate keeps the pure fragment closed and auditable"
    )]
    fn expression(&mut self, expression: &syn::Expr) -> Result<(), Ineligible> {
        match expression {
            syn::Expr::Array(array) => array
                .elems
                .iter()
                .try_for_each(|element| self.expression(element)),
            syn::Expr::Assign(assign) => {
                self.place(&assign.left)?;
                self.expression(&assign.right)
            }
            syn::Expr::Binary(binary) => match binary.op {
                syn::BinOp::And(_)
                | syn::BinOp::Or(_)
                | syn::BinOp::BitXor(_)
                | syn::BinOp::BitAnd(_)
                | syn::BinOp::BitOr(_)
                | syn::BinOp::Eq(_)
                | syn::BinOp::Lt(_)
                | syn::BinOp::Le(_)
                | syn::BinOp::Ne(_)
                | syn::BinOp::Ge(_)
                | syn::BinOp::Gt(_) => {
                    self.expression(&binary.left)?;
                    self.expression(&binary.right)
                }
                syn::BinOp::Add(_)
                | syn::BinOp::Sub(_)
                | syn::BinOp::Mul(_)
                | syn::BinOp::Div(_)
                | syn::BinOp::Rem(_)
                | syn::BinOp::Shl(_)
                | syn::BinOp::Shr(_)
                | syn::BinOp::AddAssign(_)
                | syn::BinOp::SubAssign(_)
                | syn::BinOp::MulAssign(_)
                | syn::BinOp::DivAssign(_)
                | syn::BinOp::RemAssign(_)
                | syn::BinOp::BitXorAssign(_)
                | syn::BinOp::BitAndAssign(_)
                | syn::BinOp::BitOrAssign(_)
                | syn::BinOp::ShlAssign(_)
                | syn::BinOp::ShrAssign(_) => self.reject(Effect::ProfileDependentArithmetic),
                _ => self.reject(Effect::Unsupported),
            },
            syn::Expr::Block(block) => self.block(&block.block),
            syn::Expr::Break(one) => one
                .expr
                .as_deref()
                .map_or(Ok(()), |value| self.expression(value)),
            syn::Expr::Cast(cast) => {
                self.expression(&cast.expr)?;
                symbolic_type(&cast.ty)
                    .map(|_ty| ())
                    .map_err(|_feature| Ineligible::Effect {
                        rendering: self.rendering,
                        effect: Effect::Unsupported,
                    })
            }
            syn::Expr::Continue(_) => Ok(()),
            syn::Expr::Field(field) => {
                if matches!(field.member, syn::Member::Named(_)) {
                    return self.reject(Effect::NamedField);
                }
                self.expression(&field.base)
            }
            syn::Expr::Group(group) => self.expression(&group.expr),
            syn::Expr::If(one) => {
                self.expression(&one.cond)?;
                self.block(&one.then_branch)?;
                one.else_branch
                    .as_ref()
                    .map_or(Ok(()), |(_else, branch)| self.expression(branch))
            }
            syn::Expr::Index(index) => {
                self.expression(&index.expr)?;
                self.expression(&index.index)
            }
            syn::Expr::Lit(literal) => match literal.lit {
                syn::Lit::Bool(_)
                | syn::Lit::Byte(_)
                | syn::Lit::Char(_)
                | syn::Lit::Int(_)
                | syn::Lit::Float(_) => Ok(()),
                _ => self.reject(Effect::Literal),
            },
            syn::Expr::Loop(one) => self.block(&one.body),
            syn::Expr::Paren(paren) => self.expression(&paren.expr),
            syn::Expr::Path(path) => {
                let mut segments = path.path.segments.iter();
                let Some(first) = segments.next() else {
                    return self.reject(Effect::GlobalPath);
                };
                if path.qself.is_none()
                    && segments.next().is_none()
                    && matches!(first.arguments, syn::PathArguments::None)
                    && self.local(first.ident.to_string().as_str())
                {
                    Ok(())
                } else {
                    self.reject(Effect::GlobalPath)
                }
            }
            syn::Expr::Repeat(repeat) => {
                self.expression(&repeat.expr)?;
                self.expression(&repeat.len)
            }
            syn::Expr::Return(one) => one
                .expr
                .as_deref()
                .map_or(Ok(()), |value| self.expression(value)),
            syn::Expr::Tuple(tuple) => tuple
                .elems
                .iter()
                .try_for_each(|element| self.expression(element)),
            syn::Expr::Unary(unary) => match unary.op {
                syn::UnOp::Not(_) => self.expression(&unary.expr),
                syn::UnOp::Neg(_) => self.reject(Effect::ProfileDependentArithmetic),
                syn::UnOp::Deref(_) => self.reject(Effect::Dereference),
                _ => self.reject(Effect::Unsupported),
            },
            syn::Expr::While(one) => {
                self.expression(&one.cond)?;
                self.block(&one.body)
            }
            syn::Expr::Call(_) => self.reject(Effect::Call),
            syn::Expr::MethodCall(_) => self.reject(Effect::MethodCall),
            syn::Expr::Macro(_) => self.reject(Effect::Macro),
            syn::Expr::Closure(_) => self.reject(Effect::Closure),
            syn::Expr::Async(_) | syn::Expr::Await(_) => self.reject(Effect::Async),
            syn::Expr::Unsafe(_) => self.reject(Effect::Unsafe),
            syn::Expr::Reference(_) => self.reject(Effect::Reference),
            syn::Expr::RawAddr(_) => self.reject(Effect::RawAddress),
            syn::Expr::ForLoop(_) => self.reject(Effect::ForLoop),
            syn::Expr::Range(_) => self.reject(Effect::Range),
            syn::Expr::Struct(_) => self.reject(Effect::Struct),
            syn::Expr::Try(_) | syn::Expr::TryBlock(_) => self.reject(Effect::Try),
            syn::Expr::Match(_) => self.reject(Effect::Match),
            syn::Expr::Let(_) => self.reject(Effect::Pattern),
            _ => self.reject(Effect::Unsupported),
        }
    }

    fn place(&mut self, expression: &syn::Expr) -> Result<(), Ineligible> {
        match expression {
            syn::Expr::Path(_) => self.expression(expression),
            syn::Expr::Field(field) if matches!(field.member, syn::Member::Unnamed(_)) => {
                self.place(&field.base)
            }
            syn::Expr::Index(index) => {
                self.place(&index.expr)?;
                self.expression(&index.index)
            }
            syn::Expr::Paren(paren) => self.place(&paren.expr),
            syn::Expr::Group(group) => self.place(&group.expr),
            syn::Expr::Field(_) => self.reject(Effect::NamedField),
            _ => self.reject(Effect::Reference),
        }
    }
}

fn local_name(pattern: &syn::Pat) -> Option<String> {
    match pattern {
        syn::Pat::Ident(binding) if binding.by_ref.is_none() && binding.subpat.is_none() => {
            Some(binding.ident.to_string())
        }
        syn::Pat::Wild(_) => Some(String::from("_")),
        _ => None,
    }
}

fn check_body(
    block: &syn::Block,
    arguments: &BTreeSet<String>,
    rendering: Rendering,
) -> Result<(), Ineligible> {
    let mut purity = Purity {
        scopes: vec![arguments.clone()],
        rendering,
    };
    purity.block(block)
}

#[expect(
    clippy::too_many_arguments,
    reason = "every generated identifier and proof fact is passed explicitly so rendering cannot silently derive a different one"
)]
#[expect(
    clippy::too_many_lines,
    reason = "the generated Rust proof surface is kept together so every emitted compiler guard is visible in one audit unit"
)]
fn render(
    source: &str,
    original: &str,
    mutant: &str,
    inputs: &[SymbolicType],
    output: &SymbolicType,
    harness_name: &str,
    original_name: &str,
    mutant_name: &str,
    input_trait: &str,
    output_trait: &str,
    kani_crate: &str,
    core_crate: &str,
    any_name: &str,
    same_name: &str,
    assertion_tag: &str,
    verified: Verified,
) -> String {
    let pristine = hex::encode(source.as_bytes());
    let mut rendered = format!("// njutest-pristine-v1:{pristine}");
    render_line(
        &mut rendered,
        format!(
            "\n#[cfg(kani)] extern crate kani as {kani_crate};\n#[cfg(kani)] extern crate core as {core_crate};"
        ),
    );
    rendered.push_str("\n\n#[cfg(kani)]\n");
    render_line(
        &mut rendered,
        format!("trait {input_trait}: {core_crate}::marker::Copy + {kani_crate}::Arbitrary {{}}\n"),
    );
    render_line(
        &mut rendered,
        format!("#[cfg(kani)] impl {input_trait} for () {{}}"),
    );
    for primitive in [
        "bool", "char", "i8", "i16", "i32", "i64", "i128", "u8", "u16", "u32", "u64", "u128",
        "f32", "f64",
    ] {
        render_line(
            &mut rendered,
            format!(
                "#[cfg(kani)] impl {input_trait} for {core_crate}::primitive::{primitive} {{}}"
            ),
        );
    }
    render_line(
        &mut rendered,
        format!(
            "#[cfg(kani)] impl<T: {input_trait}> {input_trait} for {core_crate}::option::Option<T> where {core_crate}::option::Option<T>: {core_crate}::marker::Copy + {kani_crate}::Arbitrary {{}}"
        ),
    );
    render_line(
        &mut rendered,
        format!(
            "#[cfg(kani)] impl<T: {input_trait}, const N: usize> {input_trait} for [T; N] where [T; N]: {core_crate}::marker::Copy + {kani_crate}::Arbitrary {{}}"
        ),
    );
    render_tuple_impls(
        &mut rendered,
        input_trait,
        &format!("{core_crate}::marker::Copy + {kani_crate}::Arbitrary"),
    );
    render_line(
        &mut rendered,
        format!(
            "#[cfg(kani)] fn {any_name}<T: {input_trait}>() -> T {{ {kani_crate}::any::<T>() }}"
        ),
    );

    render_line(
        &mut rendered,
        format!("#[cfg(kani)] trait {output_trait}: {core_crate}::cmp::Eq {{}}\n"),
    );
    render_line(
        &mut rendered,
        format!("#[cfg(kani)] impl {output_trait} for () {{}}"),
    );
    for primitive in [
        "bool", "char", "i8", "i16", "i32", "i64", "i128", "u8", "u16", "u32", "u64", "u128",
    ] {
        render_line(
            &mut rendered,
            format!(
                "#[cfg(kani)] impl {output_trait} for {core_crate}::primitive::{primitive} {{}}"
            ),
        );
    }
    render_line(
        &mut rendered,
        format!(
            "#[cfg(kani)] impl<T: {output_trait}> {output_trait} for {core_crate}::option::Option<T> {{}}"
        ),
    );
    render_line(
        &mut rendered,
        format!(
            "#[cfg(kani)] impl<T: {output_trait}, const N: usize> {output_trait} for [T; N] where [T; N]: {core_crate}::cmp::Eq {{}}"
        ),
    );
    render_tuple_impls(
        &mut rendered,
        output_trait,
        &format!("{core_crate}::cmp::Eq"),
    );
    render_line(
        &mut rendered,
        format!(
            "#[cfg(kani)] fn {same_name}<T: {output_trait}>(left: T, right: T) -> bool {{ left == right }}"
        ),
    );

    rendered.push_str("\n#[cfg(kani)]\n");
    rendered.push_str(original);
    rendered.push_str("\n#[cfg(kani)]\n");
    rendered.push_str(mutant);
    render_line(
        &mut rendered,
        format!(
            "\n#[cfg(kani)]\n#[{kani_crate}::proof]\n#[{kani_crate}::unwind({})]",
            verified.unwind()
        ),
    );
    render_line(&mut rendered, format!("fn {harness_name}() {{"));
    for (index, held) in inputs.iter().enumerate() {
        render_line(
            &mut rendered,
            format!(
                "    let __njutest_arg_{index}: {} = {any_name}();",
                held.canonical(core_crate)
            ),
        );
    }
    let arguments = (0..inputs.len())
        .map(|index| format!("__njutest_arg_{index}"))
        .collect::<Vec<_>>()
        .join(", ");
    render_line(
        &mut rendered,
        format!(
            "    let __njutest_original: {} = {original_name}({arguments});",
            output.canonical(core_crate)
        ),
    );
    render_line(
        &mut rendered,
        format!(
            "    let __njutest_mutant: {} = {mutant_name}({arguments});",
            output.canonical(core_crate)
        ),
    );
    render_line(
        &mut rendered,
        format!(
            "    {kani_crate}::assert({same_name}(__njutest_original, __njutest_mutant), {assertion_tag:?});"
        ),
    );
    rendered.push_str("}\n");
    rendered
}

fn render_line(rendered: &mut String, line: impl AsRef<str>) {
    rendered.push_str(line.as_ref());
    rendered.push('\n');
}

fn render_tuple_impls(rendered: &mut String, trait_name: &str, required: &str) {
    for width in 1..=4usize {
        let names = (0..width)
            .map(|index| format!("T{index}"))
            .collect::<Vec<_>>();
        let parameters = names
            .iter()
            .map(|name| format!("{name}: {trait_name}"))
            .collect::<Vec<_>>()
            .join(", ");
        let tuple = format!("({},)", names.join(", "));
        render_line(
            rendered,
            format!(
                "#[cfg(kani)] impl<{parameters}> {trait_name} for {tuple} where {tuple}: {required} {{}}"
            ),
        );
    }
}

/// Closed parser fixture used only by the feature-gated testkit and fuzz target.
/// Production callers can obtain a harness only through [`generate`].
#[cfg(feature = "testkit")]
pub(crate) fn parser_fixture() -> Harness {
    let mutant_id = "a".repeat(64);
    Harness {
        source: String::new(),
        name: format!("__njutest_model_{mutant_id}"),
        assertion_tag: format!("njutest-model-v1:{mutant_id}"),
        mutant_id,
        source_digest: "0".repeat(64),
        rendered_digest: "0".repeat(64),
        crate_digest: model_crate_digest(&[]),
        path: "src/lib.rs".to_owned(),
        rule: "parser-fixture".to_owned(),
        rule_version: 1,
        span: Span { start: 0, end: 1 },
        original_hex: "00".to_owned(),
        replacement_hex: "01".to_owned(),
        unwind: std::num::NonZeroU32::MIN,
        timeout_ms: std::num::NonZeroU64::MIN,
    }
}

#[cfg(test)]
mod tests {

    use std::collections::BTreeSet;
    use std::time::Duration;

    use rust_mutants::catalog::{Candidate, Mutant};
    use rust_mutants::rule::Registry;
    use rust_mutants::span::Span;

    use super::{Effect, Harness, IneligibilityKind, Ineligible, KANI_VERSION, Rendering};
    use crate::config::{Verification, Verified};

    /// The harness for `mutant`, or why the fragment does not admit it, once its source has been read.
    #[expect(
        clippy::panic_in_result_fn,
        reason = "a source these laws wrote that cannot be read at all is a failed setup, not an answer a law is about"
    )]
    fn generate(source: &[u8], mutant: &Mutant, verified: Verified) -> Result<Harness, Ineligible> {
        match super::generate(source, mutant, verified) {
            Ok(answer) => answer,
            Err(unread) => panic!("the source is read: {unread}"),
        }
    }

    fn exact_output<'a>(bytes: &'a [u8], what: &str) -> &'a str {
        match std::str::from_utf8(bytes) {
            Ok(text) => text,
            Err(error) => panic!("{what} was not UTF-8: {error}"),
        }
    }

    fn verified() -> Verified {
        Verification {
            unwind: Some(8),
            timeout: Some(Duration::from_secs(30)),
        }
        .checked()
        .expect("nonzero verifier settings")
    }

    fn mutant(source: &str, original: &str, replacement: &str) -> Mutant {
        let start = source.rfind(original).expect("mutation token");
        let end = start.checked_add(original.len()).expect("small fixture");
        let rule = Registry::canonical()
            .lookup("gt-to-ge")
            .expect("canonical rule");
        let candidate = Candidate {
            path: "src/lib.rs".to_owned(),
            rule,
            span: Span::new(
                u32::try_from(start).expect("small fixture"),
                u32::try_from(end).expect("small fixture"),
            )
            .expect("ordered span"),
            original: original.as_bytes().to_vec(),
            replacement: replacement.as_bytes().to_vec(),
            source_digest: rust_mutants::id::digest(source.as_bytes()),
        };
        let id = candidate.id().expect("coherent candidate");
        Mutant {
            index: 0,
            display_id: id.display(),
            id,
            candidate,
        }
    }

    pub(super) fn generated(source: &str, original: &str, replacement: &str) -> Harness {
        generate(
            source.as_bytes(),
            &mutant(source, original, replacement),
            verified(),
        )
        .expect("eligible fixture")
    }

    pub(super) const fn simple_source() -> &'static str {
        "pub fn clamp(x: i32) -> i32 { if x > 10 { 10 } else { x } }\n"
    }

    #[test]
    fn emits_two_renderings_and_one_self_identifying_property() {
        let source = simple_source();
        let harness = generated(source, ">", ">=");
        assert!(harness.source().contains("if x > 10"));
        assert!(harness.source().contains("if x >= 10"));
        assert_eq!(harness.unwind().get(), 8);
        assert_eq!(harness.timeout(), Duration::from_secs(30));
        assert!(harness.source().contains(harness.harness_name()));
        assert!(harness.source().contains(harness.assertion_tag()));
        assert!(harness.source().contains(harness.mutant_id()));
        assert!(harness.source().contains(&format!(
            "__njutest_core_{}::primitive::i32",
            harness.mutant_id()
        )));
        assert_eq!(
            harness.source_digest(),
            rust_mutants::id::digest(source.as_bytes())
        );
        assert_eq!(
            harness.rendered_digest(),
            rust_mutants::id::digest(harness.source().as_bytes())
        );
        syn::parse_file(harness.source()).expect("generated source remains Rust syntax");
    }

    #[test]
    fn generated_program_contains_no_unrelated_package_code() {
        let source = "fn unrelated() { dangerous_build_time_hook(); }\npub fn clamp(x: i32) -> i32 { if x > 10 { 10 } else { x } }\n";
        let harness = generated(source, ">", ">=");
        assert!(
            harness.source().starts_with("// njutest-pristine-v1:"),
            "the immutable pristine bytes are retained only as inert hex evidence"
        );
        assert!(!harness.source().contains("dangerous_build_time_hook"));
        assert!(!harness.source().contains("fn unrelated"));
        assert!(harness.source().contains("__njutest_original_"));
        assert!(harness.source().contains("__njutest_mutant_"));
    }

    #[test]
    fn signature_boundary_is_closed_and_typed() {
        let cases = [
            (
                "fn f() -> i32 { 1 > 0 }",
                IneligibilityKind::NoSymbolicInput,
            ),
            (
                "fn f(x: &i32) -> bool { x > x }",
                IneligibilityKind::InputType,
            ),
            (
                "fn f(x: i32) -> ! { x > 0; loop {} }",
                IneligibilityKind::OutputType,
            ),
            (
                "fn f(x: i32) -> f32 { x > 0; 0.0 }",
                IneligibilityKind::OutputType,
            ),
            (
                "fn f<T>(x: i32) -> i32 { x > 0; x }",
                IneligibilityKind::FunctionShape,
            ),
            (
                "async fn f(x: i32) -> i32 { x > 0; x }",
                IneligibilityKind::FunctionShape,
            ),
            (
                "unsafe fn f(x: i32) -> i32 { x > 0; x }",
                IneligibilityKind::FunctionShape,
            ),
        ];
        for (source, expected) in cases {
            let error = generate(source.as_bytes(), &mutant(source, ">", ">="), verified())
                .expect_err(source);
            assert_eq!(error.kind(), expected, "{source}: {error:?}");
        }
    }

    #[test]
    fn float_inputs_are_allowed_but_float_outputs_are_not() {
        let source = "fn positive(x: f32) -> bool { x > 0.0 }";
        let harness = generated(source, ">", ">=");
        assert!(harness.source().contains(&format!(
            "let __njutest_arg_0: __njutest_core_{}::primitive::f32",
            harness.mutant_id()
        )));
    }

    #[test]
    fn effects_are_rejected_in_both_renderings() {
        let originals = [
            ("fn f(x: i32) -> i32 { helper(x > 0) }", Effect::Call),
            ("fn f(x: i32) -> bool { x.abs() > 0 }", Effect::MethodCall),
            ("fn f(x: i32) -> bool { MAGIC > x }", Effect::GlobalPath),
            ("fn f(x: i32) -> bool { &x; x > 0 }", Effect::Reference),
            (
                "fn f(x: i32) -> bool { for _ in 0..x {} x > 0 }",
                Effect::ForLoop,
            ),
        ];
        for (source, expected) in originals {
            let error = generate(source.as_bytes(), &mutant(source, ">", ">="), verified())
                .expect_err(source);
            assert_eq!(
                error,
                Ineligible::Effect {
                    rendering: Rendering::Original,
                    effect: expected,
                },
                "{source}"
            );
        }

        let source = "fn f(x: i32) -> bool { x > 0 }";
        let error = generate(
            source.as_bytes(),
            &mutant(source, ">", ".count_ones() >"),
            verified(),
        )
        .expect_err("the edit introduces a method call");
        assert_eq!(
            error,
            Ineligible::Effect {
                rendering: Rendering::Mutant,
                effect: Effect::MethodCall,
            }
        );
    }

    #[test]
    fn typed_local_patterns_cannot_reopen_the_closed_type_domain() {
        for source in [
            "type Alias = i32; fn f(x: i32) -> bool { let y: Alias = x; y > 0 }",
            "trait Trait {} fn f(x: i32) -> bool { let y: &dyn Trait = x; x > 0 }",
            "fn f(x: i32) -> bool { let y: usize = x; x > 0 }",
            "fn f(x: i32) -> bool { let y: i32 = x; y > 0 }",
        ] {
            let error = generate(source.as_bytes(), &mutant(source, ">", ">="), verified())
                .expect_err("a typed local lies outside the canonical local-binding grammar");
            assert_eq!(
                error,
                Ineligible::Effect {
                    rendering: Rendering::Original,
                    effect: Effect::Pattern,
                },
                "{source}"
            );
        }
    }

    #[test]
    fn proof_functions_accept_only_documentation_attributes() {
        for source in [
            "#[allow(unused)] fn f(x: i32) -> bool { x > 0 }",
            "#[inline] fn f(x: i32) -> bool { x > 0 }",
            "fn f(x: i32) -> bool { #[allow(unused)] let y = x; y > 0 }",
            "#[doc = include_str!(\"README.md\")] fn f(x: i32) -> bool { x > 0 }",
            "#[doc = concat!(\"computed\")] fn f(x: i32) -> bool { x > 0 }",
            "#[doc(hidden)] fn f(x: i32) -> bool { x > 0 }",
            "#[doc] fn f(x: i32) -> bool { x > 0 }",
        ] {
            let error = generate(source.as_bytes(), &mutant(source, ">", ">="), verified())
                .expect_err("compilation-policy attributes are outside verified-v1");
            assert_eq!(
                error,
                Ineligible::Effect {
                    rendering: Rendering::Original,
                    effect: Effect::Unsupported,
                },
                "{source}"
            );
        }

        let documented = "/// pure comparison\nfn f(x: i32) -> bool { x > 0 }";
        generated(documented, ">", ">=");
    }

    #[test]
    fn profile_dependent_cfg_attributes_cannot_enter_verified_v1() {
        for source in [
            "fn f(x: i32) -> bool { #[cfg(debug_assertions)] x > 0 }",
            "fn f(x: i32) -> bool { #[cfg_attr(debug_assertions, allow(unused))] x > 0 }",
        ] {
            let error = generate(source.as_bytes(), &mutant(source, ">", ">="), verified())
                .expect_err("profile-dependent syntax must be rejected before Kani");
            assert_eq!(
                error,
                Ineligible::Effect {
                    rendering: Rendering::Original,
                    effect: Effect::Unsupported,
                },
                "{source}"
            );
        }
    }

    #[test]
    fn release_wrapping_arithmetic_cannot_enter_verified_v1() {
        let source = "fn f(x: u8) -> u8 { (x + 1) * 0 }";
        for (original, replacement) in [("+", "-"), ("*", "/")] {
            let error = generate(
                source.as_bytes(),
                &mutant(source, original, replacement),
                verified(),
            )
            .expect_err("profile-dependent arithmetic must be refused before Kani");
            assert_eq!(
                error,
                Ineligible::Effect {
                    rendering: Rendering::Original,
                    effect: Effect::ProfileDependentArithmetic,
                }
            );
        }
    }

    #[test]
    fn real_kani_068_never_receives_profile_dependent_arithmetic_when_requested() {
        if std::env::var_os("NJUTEST_REAL_KANI").is_none() {
            return;
        }
        let source = "fn f(x: u8) -> u8 { (x + 1) * 0 }";
        assert_eq!(
            generate(source.as_bytes(), &mutant(source, "+", "-"), verified())
                .expect_err("the unsound release-only equivalence must not reach Kani"),
            Ineligible::Effect {
                rendering: Rendering::Original,
                effect: Effect::ProfileDependentArithmetic,
            }
        );
    }

    #[test]
    fn source_and_candidate_are_independently_rederived() {
        let source = "fn f(x: i32) -> bool { x > 0 }";
        let mut one = mutant(source, ">", ">=");
        one.candidate.source_digest = String::from("0");
        assert_eq!(
            generate(source.as_bytes(), &one, verified()).expect_err("stale digest"),
            Ineligible::SourceDigest
        );

        let mut two = mutant(source, ">", ">=");
        let forged = rust_mutants::id::MutantId::try_from(rust_mutants::id::digest(b"wrong"))
            .expect("digest is a canonical mutant identity");
        two.display_id = forged.display();
        two.id = forged;
        assert_eq!(
            generate(source.as_bytes(), &two, verified()).expect_err("forged id"),
            Ineligible::Identity
        );
    }

    #[test]
    fn every_refusal_kind_is_in_the_closed_ledger() {
        let mut unique = BTreeSet::new();
        for kind in IneligibilityKind::ALL {
            unique.insert(format!("{kind:?}"));
        }
        assert_eq!(unique.len(), IneligibilityKind::ALL.len());
    }

    #[test]
    fn real_kani_068_typechecks_and_proves_the_generated_harness_when_requested() {
        if std::env::var_os("NJUTEST_REAL_KANI").is_none() {
            return;
        }
        let source = simple_source();
        let harness = generated(source, ">", ">=");
        let temporary = tempfile::tempdir().expect("temporary crate");
        std::fs::create_dir_all(temporary.path().join("src")).expect("src directory");
        std::fs::write(
            temporary.path().join("Cargo.toml"),
            "[package]\nname = \"njutest-model-fixture\"\nversion = \"0.0.0\"\nedition = \"2024\"\n\n[workspace]\n",
        )
        .expect("manifest");
        std::fs::write(temporary.path().join("src/lib.rs"), harness.source()).expect("source");

        let version = std::process::Command::new("cargo")
            .args(["kani", "--version"])
            .output()
            .expect("cargo kani is installed");
        assert!(version.status.success(), "cargo kani --version failed");
        let version_stdout = exact_output(&version.stdout, "cargo kani --version stdout");
        assert!(
            version_stdout.contains(KANI_VERSION),
            "the campaign pins Kani {KANI_VERSION}: {version_stdout}"
        );
        let result = std::process::Command::new("cargo")
            .current_dir(temporary.path())
            .args([
                "kani",
                "--harness",
                harness.harness_name(),
                "--exact",
                "-Z",
                "unstable-options",
                "--export-json",
                "kani.json",
            ])
            .output()
            .expect("run Kani");
        let stdout = exact_output(&result.stdout, "cargo kani stdout");
        let stderr = exact_output(&result.stderr, "cargo kani stderr");
        assert!(
            result.status.success(),
            "generated proof failed:\nstdout:\n{stdout}\nstderr:\n{stderr}"
        );
    }

    #[test]
    fn source_context_cannot_rebind_an_admitted_type_before_extraction() {
        for source in [
            "struct Option<T>(T);\nfn identity(x: Option<i32>) -> Option<i32> { if 1 > 0 { x } else { x } }\n",
            "struct i32(bool);\nfn identity(x: i32) -> i32 { if 1 > 0 { x } else { x } }\n",
            "type i32 = bool;\nfn identity(x: i32) -> i32 { if 1 > 0 { x } else { x } }\n",
            "struct Alias; use crate::Alias as i32;\nfn identity(x: i32) -> i32 { if 1 > 0 { x } else { x } }\n",
            "mod names {} use crate::names::*;\nfn identity(x: i32) -> i32 { if 1 > 0 { x } else { x } }\n",
            "macro_rules! names { () => {} }\nfn identity(x: i32) -> i32 { if 1 > 0 { x } else { x } }\n",
            "extern crate self as core;\nfn identity(x: core::primitive::i32) -> core::primitive::i32 { if 1 > 0 { x } else { x } }\n",
            "mod std {}\nfn identity(x: std::primitive::i32) -> std::primitive::i32 { if 1 > 0 { x } else { x } }\n",
        ] {
            let error = generate(source.as_bytes(), &mutant(source, ">", ">="), verified())
                .expect_err("an extracted type must retain its subject-crate resolution");
            assert_eq!(error, Ineligible::NameCollision, "{source}");
        }
    }

    #[test]
    fn real_kani_068_ignores_subject_kani_and_core_modules_when_requested() {
        if std::env::var_os("NJUTEST_REAL_KANI").is_none() {
            return;
        }
        let source = "mod kani {}\nmod core {}\npub fn clamp(x: i32) -> i32 { if x > 10 { 10 } else { x } }\n";
        let harness = generated(source, ">", ">=");
        let temporary = tempfile::tempdir().expect("temporary crate");
        std::fs::create_dir_all(temporary.path().join("src")).expect("src directory");
        std::fs::write(
            temporary.path().join("Cargo.toml"),
            "[package]\nname = \"njutest-model-shadowed-kani\"\nversion = \"0.0.0\"\nedition = \"2024\"\n\n[workspace]\n",
        )
        .expect("manifest");
        std::fs::write(temporary.path().join("src/lib.rs"), harness.source()).expect("source");

        let result = std::process::Command::new("cargo")
            .current_dir(temporary.path())
            .args(["kani", "--harness", harness.harness_name()])
            .output()
            .expect("run Kani");
        let stderr = exact_output(&result.stderr, "cargo kani stderr");
        assert!(
            result.status.success(),
            "private external-crate aliases must bypass subject modules named kani and core:\n{stderr}"
        );
    }
}
