# SPDX-FileCopyrightText: 2026 njutest contributors
# SPDX-License-Identifier: MIT OR Apache-2.0

[package]
name = "fixture-app"
version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
fixture-core = { path = "../core" }

[[bin]]
name = "fixture-app"
path = "src/main.rs"
