// SPDX-FileCopyrightText: 2026 mjutest contributors
// SPDX-License-Identifier: MIT OR Apache-2.0

//! A workspace a test can hand to the thing it is testing.
//!
//! Copying a fixture is the right move when a test is about one of the
//! recorded projects. It is the wrong move when a test is about *one*
//! property — a package that does not compile, a suite with no tests at all,
//! a repository with a commit — because then the reader has to go and find
//! the fixture to know what the test is even saying.
//!
//! A [`Repo`] says it in the test. The tree lives in a temporary directory
//! that goes away with the value, and every project it writes is
//! self-contained: its own `[workspace]` table so cargo does not look
//! upwards, its own committed lock file, and no dependencies at all, so it
//! builds `--locked --offline` on a machine with no network.

#![expect(
    clippy::expect_used,
    reason = "a builder for tests reports a setup failure by panicking: a test that cannot \
              write its own tree has nothing left to assert"
)]

use std::path::{Path, PathBuf};
use std::process::Command;

/// A temporary cargo workspace.
#[derive(Debug)]
pub struct Repo {
    root: PathBuf,
    // The directory is removed when this is dropped, which is what bounds a
    // test's mess to the test.
    _dir: tempfile::TempDir,
}

/// One package being described.
#[derive(Debug)]
pub struct Package<'a> {
    repo: &'a Repo,
    name: String,
}

impl Repo {
    /// An empty temporary directory to build a workspace in.
    ///
    /// # Panics
    ///
    /// When a temporary directory cannot be made, which a test cannot
    /// continue without.
    #[must_use]
    pub fn new() -> Self {
        let dir = tempfile::Builder::new()
            .prefix("mjutest-repo-")
            .tempdir()
            .expect("a temporary directory");
        let root = dir.path().join("workspace");
        std::fs::create_dir_all(&root).expect("the workspace directory");
        Self { root, _dir: dir }
    }

    /// The workspace root.
    #[must_use]
    pub fn root(&self) -> &Path {
        &self.root
    }

    /// Writes `contents` at `relative`, making the directories above it.
    ///
    /// # Panics
    ///
    /// When the file cannot be written.
    pub fn write(&self, relative: &str, contents: &str) {
        let path = self.root.join(relative);
        if let Some(parent) = path.parent() {
            std::fs::create_dir_all(parent).expect("the directory");
        }
        std::fs::write(&path, contents).expect("the file");
    }

    /// Starts a package named `name` at the workspace root.
    ///
    /// The manifest carries an empty `[workspace]` table and no
    /// dependencies, and a lock file naming only itself, so the project
    /// builds offline against no registry.
    #[must_use]
    pub fn package(&self, name: &str) -> Package<'_> {
        self.write(
            "Cargo.toml",
            &format!(
                "# SPDX-FileCopyrightText: 2026 mjutest contributors\n\
                 # SPDX-License-Identifier: MIT OR Apache-2.0\n\n\
                 [package]\n\
                 name = \"{name}\"\n\
                 version = \"0.1.0\"\n\
                 edition = \"2024\"\n\
                 publish = false\n\n\
                 [workspace]\n\n\
                 [dependencies]\n"
            ),
        );
        self.write(
            "Cargo.lock",
            &format!(
                "# This file is automatically @generated by Cargo.\n\
                 # It is not intended for manual editing.\n\
                 version = 4\n\n\
                 [[package]]\n\
                 name = \"{name}\"\n\
                 version = \"0.1.0\"\n"
            ),
        );
        Package {
            repo: self,
            name: name.to_owned(),
        }
    }

    /// Makes the tree a git repository with one commit holding everything
    /// written so far.
    ///
    /// Built with git's own plumbing, so the fixture is the same on every
    /// machine: `commit-tree` writes a commit without consulting anybody's
    /// configuration, and the identity comes from the environment.
    ///
    /// # Panics
    ///
    /// When git is not there or refuses, which a test asking for a
    /// repository cannot continue without.
    pub fn commit(&self) {
        let run = |args: &[&str]| -> String {
            let output =
                Command::new("git")
                    .args(args)
                    .current_dir(&self.root)
                    .env_clear()
                    .envs(std::env::vars_os().filter(|(key, _)| {
                        matches!(key.to_string_lossy().as_ref(), "PATH" | "HOME")
                    }))
                    .env("GIT_AUTHOR_NAME", "fixture")
                    .env("GIT_AUTHOR_EMAIL", "fixture@example.invalid")
                    .env("GIT_AUTHOR_DATE", "2026-09-05T00:00:00Z")
                    .env("GIT_COMMITTER_NAME", "fixture")
                    .env("GIT_COMMITTER_EMAIL", "fixture@example.invalid")
                    .env("GIT_COMMITTER_DATE", "2026-09-05T00:00:00Z")
                    .output()
                    .expect("git runs");
            assert!(
                output.status.success(),
                "git {args:?}: {}",
                String::from_utf8_lossy(&output.stderr)
            );
            String::from_utf8_lossy(&output.stdout).trim().to_owned()
        };
        if !self.root.join(".git").is_dir() {
            run(&["init", "--initial-branch=main"]);
        }
        run(&["add", "-A"]);
        let tree = run(&["write-tree"]);
        let commit = run(&["commit-tree", &tree, "-m", "fixture"]);
        run(&["update-ref", "refs/heads/main", &commit]);
        run(&["symbolic-ref", "HEAD", "refs/heads/main"]);
    }
}

impl Default for Repo {
    fn default() -> Self {
        Self::new()
    }
}

impl Package<'_> {
    /// The workspace this package is in.
    #[must_use]
    pub const fn repo(&self) -> &Repo {
        self.repo
    }

    /// Writes `src/lib.rs` with the SPDX header and a crate doc.
    pub fn lib(&self, body: &str) {
        self.repo.write("src/lib.rs", &source(&self.name, body));
    }

    /// Writes an integration test target at `tests/<name>.rs`.
    pub fn integration_test(&self, name: &str, body: &str) {
        self.repo
            .write(&format!("tests/{name}.rs"), &source(name, body));
    }
}

/// A Rust file with the header every file in this repository carries, so a
/// tree a test builds passes the same conventions the fixtures do.
fn source(name: &str, body: &str) -> String {
    format!(
        "// SPDX-FileCopyrightText: 2026 mjutest contributors\n\
         // SPDX-License-Identifier: MIT OR Apache-2.0\n\n\
         //! {name}, written by a test.\n\n\
         {body}"
    )
}
